version: '3.9'
services:
  wewantya-mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - routing_routing
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
 
  wewantya-node:
    image: node:lts-slim
    working_dir: /app
    command: /bin/sh -c 'npm install && npm run start'
    ports:
      - '3006:3006'
    volumes:
      - './src:/app'
    depends_on:
      wewantya-mongodb:
        condition: service_started
    networks:
      - routing_routing
    environment:
      - MONGO_URL=mongodb://wewantya-mongodb:27017/emailwewantya
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wewantya.rule=Host(`api.wewantya.fr`)"
      - "traefik.http.routers.wewantya.entrypoints=websecure"
      - "traefik.http.routers.wewantya.tls.certresolver=myresolver"
      
networks:
  routing_routing:
    external: true