# version: '3.9'
# services:
#   wewantya-mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     networks:
#       - routing_routing
#     ports:
#       - "27017:27017"
#     volumes:
#       - ./db:/data/db
 
#   wewantya-node:
#     image: node:lts-slim
#     working_dir: /app
#     command: /bin/sh -c 'npm install && npm run start'
#     ports:
#       - '3006:3006'
#     volumes:
#       - './src:/app'
#     depends_on:
#       wewantya-mongodb:
#         condition: service_started
#     networks:
#       - routing_routing
#     environment:
#       - MONGO_URL=mongodb://wewantya-mongodb:27017/emailwewantya
#     labels:
#       - "traefik.enable=true"
#       - "traefik.http.routers.wewantya.rule=Host(`api.wewantya.fr`)"
#       - "traefik.http.routers.wewantya.entrypoints=websecure"
#       - "traefik.http.routers.wewantya.tls.certresolver=myresolver"
      
# networks:
#   routing_routing:
#     external: true

version: '3.9'
services:
  scenium-mongodb:
    image: mongo:latest
    container_name: scenium-mongodb
    networks:
      - rooting
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
 
  scenium-node:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: scenium-node
    working_dir: /app
    command: /bin/sh -c 'npm install && npm run start'
    ports:
      - '5001:5001'
    volumes:
      - './:/app'
    depends_on:
      scenium-mongodb:
        condition: service_started
    networks:
      - rooting
    environment:
      - MONGO_URL=mongodb://scenium-mongodb:27017/sceniumdb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.scenium.rule=Host(`scenium.devprod.fr`)"
      - "traefik.http.routers.scenium.entrypoints=https"
      - "traefik.http.routers.scenium.tls.certresolver=letsencrypt"
      - "traefik.http.services.scenium.loadbalancer.server.port=5001"
networks:
  rooting:
    external: true